# Stage 1 Build the app
FROM mcr.microsoft.comdotnetsdk8.0 AS build
WORKDIR src
COPY . .
RUN dotnet publish -c Release -o appout

# Stage 2 Run the app
FROM mcr.microsoft.comdotnetaspnet8.0
WORKDIR app
COPY --from=build appout .
ENV ASPNETCORE_URLS=http+10000
EXPOSE 10000
ENTRYPOINT [dotnet, AttendanceSystem.dll]
